"""Mock inputs for each prompt module in this directory, and the user prompts built from them.

Run `python prompts/example.py` to print every user prompt.
"""

import ascribe_prompt
import atomic_extract_prompt
import atomic_judge_precision_prompt
import atomic_judge_recall_prompt
import ce_prompt
import cot_prompt
import default_prompt
import refinement_prompt
import sig_classify_prompt
import sp_prompt

# Example transcript of an encounter (mock).
MOCK_TRANSCRIPT = [
    "สวัสดีครับ วันนี้มาด้วยเรื่องอะไรครับ",
    "ไอมาสามวันค่ะ มีเสมหะสีเหลือง แต่ไม่มีไข้ค่ะ",
    "เคยแพ้ยาอะไรไหมครับ",
    "แพ้ Amoxicillin ค่ะ กินแล้วขึ้นผื่น",
    "ครับ หมอจะให้ยาละลายเสมหะไปทานนะครับ ถ้าไม่ดีขึ้นภายในหนึ่งสัปดาห์ให้กลับมาตรวจใหม่",
]

# Example reference atomic facts for the mock consultation above.
MOCK_ATOMIC_FACTS = [
    {
        "atomic_bullet": "ผู้ป่วยมีอาการไอมา 3 วัน",
        "evidence_note": "Patient states 'ไอมาสามวันค่ะ'",
        "medical_significance": "Diagnosis-impacting",
    },
    {
        "atomic_bullet": "ผู้ป่วยมีเสมหะสีเหลือง",
        "evidence_note": "Patient states 'มีเสมหะสีเหลือง'",
        "medical_significance": "Diagnosis-impacting",
    },
    {
        "atomic_bullet": "ผู้ป่วยไม่มีไข้",
        "evidence_note": "Patient states 'แต่ไม่มีไข้ค่ะ'",
        "medical_significance": "Diagnosis-impacting",
    },
    {
        "atomic_bullet": "ผู้ป่วยแพ้ยา Amoxicillin",
        "evidence_note": "Patient states 'แพ้ Amoxicillin ค่ะ'",
        "medical_significance": "Required",
    },
    {
        "atomic_bullet": "ผู้ป่วยมีผื่นขึ้นหลังรับประทาน Amoxicillin",
        "evidence_note": "Patient states 'แพ้ Amoxicillin ค่ะ กินแล้วขึ้นผื่น'",
        "medical_significance": "Required",
    },
    {
        "atomic_bullet": "แพทย์จะให้ยาละลายเสมหะแก่ผู้ป่วย",
        "evidence_note": "Doctor states 'หมอจะให้ยาละลายเสมหะไปทานนะครับ'",
        "medical_significance": "Treatment-impacting",
    },
    {
        "atomic_bullet": "แพทย์แนะนำให้ผู้ป่วยกลับมาตรวจใหม่หากอาการไม่ดีขึ้นภายใน 1 สัปดาห์",
        "evidence_note": "Doctor states 'ถ้าไม่ดีขึ้นภายในหนึ่งสัปดาห์ให้กลับมาตรวจใหม่'",
        "medical_significance": "Good for follow-up",
    },
]

# Example atomic facts generated by the atomic-extract prompt.
MOCK_GENERATED_BULLETS = {
    "facts": [
        {"bullet": "ผู้ป่วยมีอาการไอ"},
        {"bullet": "ผู้ป่วยมีเสมหะสีเหลือง"},
        {"bullet": "ผู้ป่วยไม่มีไข้"},
        {"bullet": "ผู้ป่วยแพ้ยา Amoxicillin โดยมีผื่นขึ้น"},
        {"bullet": "แพทย์จะให้ยาละลายเสมหะ Bromhexine แก่ผู้ป่วย"},
        {"bullet": "แพทย์จะให้ยาปฏิชีวนะแก่ผู้ป่วย"},
    ]
}

# Example generated SOAP summary for the mock consultation above.
MOCK_ORIGINAL_SUMMARY = {
    "history_of_present_illness": [
        "ผู้ป่วยมีอาการไอ มีเสมหะสีเหลือง ไม่มีไข้",
        "ผู้ป่วยแพ้ยา Amoxicillin โดยมีผื่นขึ้น",
    ],
    "physical_exam": [],
    "results": [],
    "assessment_and_plan": [
        "แพทย์จะให้ยาละลายเสมหะ Bromhexine แก่ผู้ป่วย",
    ],
}


if __name__ == "__main__":
    mock_bullets = [f["atomic_bullet"] for f in MOCK_ATOMIC_FACTS]
    generated_bullets = [f["bullet"] for f in MOCK_GENERATED_BULLETS["facts"]]

    print("=== default_prompt ===")
    print(default_prompt.build_user_prompt(MOCK_TRANSCRIPT))
    print()
    print("=== cot_prompt ===")
    print(cot_prompt.build_user_prompt(MOCK_TRANSCRIPT))
    print()
    print("=== ascribe_prompt ===")
    print(ascribe_prompt.build_user_prompt(MOCK_TRANSCRIPT))
    print()
    print("=== atomic_extract_prompt ===")
    print(atomic_extract_prompt.build_user_prompt(MOCK_TRANSCRIPT))
    print()
    print("=== sig_classify_prompt ===")
    print(sig_classify_prompt.build_user_prompt(mock_bullets))
    print()
    print("=== atomic_judge_recall_prompt ===")
    print(atomic_judge_recall_prompt.build_user_prompt(mock_bullets, generated_bullets))
    print()
    print("=== atomic_judge_precision_prompt ===")
    print(atomic_judge_precision_prompt.build_user_prompt(mock_bullets, generated_bullets))
    print()
    print("=== ce_prompt ===")
    print(ce_prompt.build_user_prompt(MOCK_ORIGINAL_SUMMARY, mock_bullets))
    print()
    print("=== sp_prompt ===")
    print(sp_prompt.build_user_prompt(MOCK_ORIGINAL_SUMMARY, MOCK_TRANSCRIPT))
    print()
    print("=== refinement_prompt ===")
    print(refinement_prompt.build_user_prompt(MOCK_ORIGINAL_SUMMARY, MOCK_TRANSCRIPT))
